%% <module> faldo
% Autogenerated by ontol_bridge_to_schema
% Example: blip -i biopax-level2.owl ontol-schema  -local biopax2 -ns "http://www.biopax.org/release/biopax-level2.owl#"

:-module(faldo,['BothStrandsPosition'/1,'ExactPosition'/1,'ForwardStrandPosition'/1,'FuzzyPosition'/1,'InBetweenPosition'/1,'InRangePosition'/1,'OneOfPosition'/1,'Position'/1,'Region'/1,'ReverseStrandPosition'/1,'StrandedPosition'/1,after/2,before/2,begin/2,end/2,location/2,reference/2,position/2,op(300,xfy,after),op(300,xfy,before),op(300,xfy,begin),op(300,xfy,end),op(300,xfy,location),op(300,xfy,reference),op(300,xfy,position)]).
:-use_module(bio(owl_util)).
:-use_module(semweb(rdf_db)).
:-use_module(semweb(rdfs)).
:-op(300,xfy,after).
:-op(300,xfy,before).
:-op(300,xfy,begin).
:-op(300,xfy,end).
:-op(300,xfy,location).
:-op(300,xfy,reference).
:-op(300,xfy,position).
faldo:'BothStrandsPosition'(_G1490):-rdfs_individual_of(_G1490,'http://biohackathon.org/resource/faldo#BothStrandsPosition').
faldo:'ExactPosition'(_G1490):-rdfs_individual_of(_G1490,'http://biohackathon.org/resource/faldo#ExactPosition').
faldo:'ForwardStrandPosition'(_G1490):-rdfs_individual_of(_G1490,'http://biohackathon.org/resource/faldo#ForwardStrandPosition').
faldo:'FuzzyPosition'(_G1490):-rdfs_individual_of(_G1490,'http://biohackathon.org/resource/faldo#FuzzyPosition').
faldo:'InBetweenPosition'(_G1490):-rdfs_individual_of(_G1490,'http://biohackathon.org/resource/faldo#InBetweenPosition').
faldo:'InRangePosition'(_G1490):-rdfs_individual_of(_G1490,'http://biohackathon.org/resource/faldo#InRangePosition').
faldo:'OneOfPosition'(_G1490):-rdfs_individual_of(_G1490,'http://biohackathon.org/resource/faldo#OneOfPosition').
faldo:'Position'(_G1490):-rdfs_individual_of(_G1490,'http://biohackathon.org/resource/faldo#Position').
faldo:'Region'(_G1490):-rdfs_individual_of(_G1490,'http://biohackathon.org/resource/faldo#Region').
faldo:'ReverseStrandPosition'(_G1490):-rdfs_individual_of(_G1490,'http://biohackathon.org/resource/faldo#ReverseStrandPosition').
faldo:'StrandedPosition'(_G1490):-rdfs_individual_of(_G1490,'http://biohackathon.org/resource/faldo#StrandedPosition').
faldo:after(_G1490,_G1493):-rdf_has(_G1490,'http://biohackathon.org/resource/faldo#after',_G1493).
faldo:before(_G1490,_G1493):-rdf_has(_G1490,'http://biohackathon.org/resource/faldo#before',_G1493).
faldo:begin(_G1490,_G1493):-rdf_has(_G1490,'http://biohackathon.org/resource/faldo#begin',_G1493).
faldo:end(_G1490,_G1493):-rdf_has(_G1490,'http://biohackathon.org/resource/faldo#end',_G1493).
faldo:location(_G1490,_G1493):-rdf_has(_G1490,'http://biohackathon.org/resource/faldo#location',_G1493).
faldo:reference(_G1490,_G1493):-rdf_has(_G1490,'http://biohackathon.org/resource/faldo#reference',_G1493).
faldo:position(_G1490,_G1493):-rdf_has(_G1490,'http://biohackathon.org/resource/faldo#position',_G1522),rdf_literal_to_native(_G1522,_G1493).
